Repository dknowles2/pyschlage, pull requests merged in 2024-06, with the labels that each got.

#139 Add 5 minutes as an option
  pyschlage/lock.py
Labels: enhancement

#140 Run mypy checks and fix all problems found with mypy
  .devcontainer.json
  .github/workflows/build-and-test.yml
  .github/workflows/matchers/mypy.json
  mypy.ini
  pyschlage/auth.py
  pyschlage/code.py
  pyschlage/common.py
  pyschlage/lock.py
  pyschlage/user.py
  requirements-test.txt
Labels: cleanup

#141 Replace flake8 with ruff
  .devcontainer.json
  .github/workflows/build-and-test.yml
  .pre-commit-config.yaml
  pyschlage/lock.py
  pyschlage/log.py
  requirements-test.txt
  tests/test_code.py
  tests/test_common.py
  tests/test_lock.py
Labels: enhancement, cleanup

#142 Run mypy against everything
  .github/workflows/build-and-test.yml
Labels: cleanup

#143 Upgrade required python to 3.12
  .devcontainer.json
  .github/workflows/build-and-test.yml
  .github/workflows/publish-python.yml
  .readthedocs.yaml
  pyproject.toml
  pyschlage/code.py
  pyschlage/log.py
Labels: breaking
