Repository dknowles2/pyschlage, pull requests merged in 2024-11, with the labels that each got.

#203 Fix adding/updating access codes.
  .vscode/settings.json
  pyschlage/code.py
  tests/conftest.py
  tests/test_code.py
Labels: bug

#206 Update ruff-pre-commit
  .pre-commit-config.yaml
Labels: cleanup

#207 Teach last_changed_by about 1-touch locking
  pyschlage/lock.py
  tests/test_lock.py
Labels: enhancement

#208 Clarify a comment
  pyschlage/code.py
Labels: cleanup
